branch-defaults:
  default:
    environment: wealth-management-env
    group_suffix: null
  feature/recommendation-llm-system-v2:
    environment: wealth-mgmt-api
    group_suffix: null
global:
  application_name: wealth-management-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
